import {
  TextProvider,
  ImageProvider,
  ProviderType,
  TextResponse,
  ImageResponse,
  TextGenerationOptions,
  ImageGenerationOptions
} from '../../types';

/**
 * Mock text provider for local development
 * Returns simulated responses without calling external APIs
 */
export class MockTextProvider implements TextProvider {
  readonly name = 'Mock Text Provider';
  readonly type = ProviderType.TEXT;
  private delay: number;

  constructor(delay: number = 1000) {
    this.delay = delay;
  }

  isConfigured(): boolean {
    return true;
  }

  async healthCheck(): Promise<boolean> {
    return true;
  }

  async generateText(prompt: string, options?: TextGenerationOptions): Promise<TextResponse> {
    // Simulate network delay
    await this.sleep(this.delay);

    const mockResponses = [
      `This is a mock response to your prompt: "${prompt.substring(0, 50)}...". In a real scenario, this would be generated by an AI model like Gemini or Claude.`,
      `Based on your request "${prompt.substring(0, 50)}...", here's a creative response. This is simulated content for development purposes.`,
      `Mock AI Response: I understand you're asking about "${prompt.substring(0, 50)}...". This is placeholder text that would be replaced by actual AI-generated content.`
    ];

    const randomResponse = mockResponses[Math.floor(Math.random() * mockResponses.length)];

    return {
      text: randomResponse,
      provider: this.name,
      model: 'mock-model',
      tokensUsed: Math.floor(Math.random() * 500) + 100,
      finishReason: 'stop',
      metadata: {
        isMock: true,
        originalPrompt: prompt.substring(0, 100)
      }
    };
  }

  async *generateStream(prompt: string, options?: TextGenerationOptions): AsyncGenerator<string> {
    const response = await this.generateText(prompt, options);
    const words = response.text.split(' ');

    for (const word of words) {
      await this.sleep(50);
      yield word + ' ';
    }
  }

  private sleep(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
  }
}

/**
 * Mock image provider for local development
 * Returns placeholder images without calling external APIs
 */
export class MockImageProvider implements ImageProvider {
  readonly name = 'Mock Image Provider';
  readonly type = ProviderType.IMAGE;
  private delay: number;

  constructor(delay: number = 1000) {
    this.delay = delay;
  }

  isConfigured(): boolean {
    return true;
  }

  async healthCheck(): Promise<boolean> {
    return true;
  }

  async generateImage(prompt: string, options?: ImageGenerationOptions): Promise<ImageResponse> {
    // Simulate network delay
    await this.sleep(this.delay);

    const width = options?.width || 512;
    const height = options?.height || 512;

    // Generate a placeholder image URL
    const placeholderUrl = `https://via.placeholder.com/${width}x${height}/3b82f6/ffffff?text=${encodeURIComponent(prompt.substring(0, 20))}`;

    return {
      imageUrl: placeholderUrl,
      provider: this.name,
      model: 'mock-image-model',
      width,
      height,
      seed: options?.seed || Math.floor(Math.random() * 1000000),
      metadata: {
        isMock: true,
        originalPrompt: prompt.substring(0, 100),
        note: 'This is a placeholder image. In production, this would be generated by FLUX or Stable Diffusion.'
      }
    };
  }

  private sleep(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
  }
}
